version: '2'

services:
    static:
        restart: always
        build: ./static
        volumes:
            - ./static:/usr/share/static

    nginx:
        restart: always
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes_from:
            - static

    django:
        restart: always
        build: ./django
        command: python manage.py runserver 0.0.0.0:8000
        expose:
            - "8000"
        volumes:
            - ./django:/code/
